version: 2.1

orbs:
  aws-s3: circleci/aws-s3@3.0

jobs:
  build_website:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "b2:23:ce:56:3e:ef:20:5a:5a:4a:8d:04:4d:b7:cb:a7"
      - run: |-
          git clone https://github.com/PixelToast/mkdocs-material-insiders.git --depth=1
          pip install ./mkdocs-material-insiders
          pip install -r requirements.txt
          export PYTHONPATH=`pwd`
          mkdocs build
      - aws-s3/sync:
          from: site/
          to: s3://femboy
      - run: aws cloudfront create-invalidation --distribution-id $NOTES_CF_DISTRIBUTION --paths "/*"

workflows:
  master:
    jobs:
      - build_website
    when:
      equal: [ "master", << pipeline.git.branch >> ]
